config/routes.rb
Rails.application.routes.draw do

  root 'hello#index'

  resources :applications
  get "signin" => "auth#signin"
  get "signout" => "auth#signout"
  post "signin" => "auth#login"
  get 'users/new'
  resources :his
  post 'users/create'
  get '/applications/:id', to: 'applications#show', as: 'app'

end

app/models/application.rb
class Application < ActiveRecord::Base
	#include Appliable
	include Statesman::Adapters::ActiveRecordQueries

	belongs_to :user
	has_many :terms, as: :termable
	has_many :application_transitions
	has_many :comments
	validates :genre, presence: true
	#only complete if the writing sample is here and the reference has a path, 
	#meaning the letter of rec is uploaded
	#todo move to a concern
	def is_complete?
		app = Application.find(self.id)
		if app.writing_sample && app.location_reference
			true
		else
			false
		end
	end

	def generate_letter
		params = {}
		if printable_recommendation?
			params["application_id"] = self.id
			params["doc_type"] = "letter"
			params["content"] = self.recommendation_letter			
			#PdfWorker.perform_async(params)
		end
	end

	def generate_sample
		params = {}
		if printable_sample?
			params["application_id"] = self.id
			params["doc_type"] = "sample"
			PdfWorker.perform_async(params)
		end
	end


	def printable_recommendation?
		true unless self.recommendation_letter.blank?
	end

	def printable_sample?
		true unless self.writing_sample.blank?
	end

  	def state_machine
    	@state_machine ||= ApplicationStateMachine.new(self, transition_class: ApplicationTransition)
  	end

	def self.initial_state
    	:pending
  	end
  	def self.transition_class
    	ApplicationTransition
  	end

end

# Possible status
# pending (the application has begun
# completed (the application is complete): writing sample, uploaded letter of rec, 
# invited (we are inviting them to join)
# rejected (we don’t like them)
# declined
# accepted (student has accepted application)
# withdrawn (student paid, then fled)
# archived (don't display)
=begin
 state transitions

	
=end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController

	def create
		@app = Application.new(app_params)
		@app.save
	end

	# todo filter by existence of state machine
	# 
	def index
		if session[:role] == "applicant"
			@applications = Application.where(user_id: sessions[user_id]).reject{ |r| r.state_machine.current_state=='archived'}
		elsif session[:role] == "mentor"
			@applications = Application.where(genre:'fiction').reject{ |r| r.state_machine.current_state=='archived'}
		elsif session[:role] == 'admin'	
	    	@applications = Application.all.reject{ |r| r.state_machine.current_state=='archived'} #where status!=archive
		end
	end

	def new
		@app = Application.new
	end

	def show
  		@app = Application.find_by(id: params[:id])
  		if @app.nil?
  			index
    		render "index" and return
		end
		render "show"
	end
	private

    def app_params
         params.require(:application).permit(:genre, :best_film, :writing_sample)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applications/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Atheneum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Listing Applications</h1>
 
<table>
  <tr>
    <th>Genre</th>
    <th>Summary</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <!--     <td><percent= link_to "Edit", #edit_app_path(app) percent></td>-->
 
<% @applications.each do |app| %>
  <tr>

    <td><%= app.genre %></td>
    <td><%= app.family_hero %></td>
    <td><%= link_to "Show", app %></td>
    <td><%= link_to "Remove", app, method: :delete, data: { confirm: "Are you sure?" } %></td>
  </tr>
<% end %>
</table>
 
<br>
 
</body>
</html>

app/views/applications/new.html.erb
<%= form_for @app, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
Genre  <%= f.text_field :genre %> <br/>
Best 3 films <%= f.text_field :best_film %><br/>
Writing Sample<br/>
<%= f.text_area :writing_sample, size: "60x12" %><br/>
Community Role<br/>
<%= f.text_area :community_role, size: "60x12" %><br/>
Conversation starter?
 <%= f.text_field :conversation_starter %>  <br/>,
 How are next 11 months at Atheneum essential to your writing?<br/>
 <%= f.text_area :essential_to_writing %> <br/>,
Family Hero <%= f.text_field :family_hero %> <br/>,
Favorite Quiet Meal <%= f.text_field :favorite_quiet_meal %> <br/>,
 Fiction Character <%= f.text_field :fiction_character %> <br/>,
 Film Character<%= f.text_field :film_character %>  <br/>,
Head turning Fact <%= f.text_field :head_turner %>  <br/>,
 3 words to describe you <%= f.text_field :personality_word %> <br/>,
Political Hero <%= f.text_field :political_hero %> political_hero: <br/>,
	 <%= f.text_field :studied_with %> studied_with: <br/>,
What Time period?  <%= f.text_field :time_period %> <br/>
  <%= f.submit "Create" %>
<% end %>

app/views/applications/show.html.erb
<!DOCTYPE html>
 <html>
 <head>
 	<title>Application for <%=@app.genre %></title>
 </head>
 <body>
 This application is for #link user
 <table>
 <tr><td>Genre</td>
   <td><%= @app.genre %></td>
   <tr><td>Family Hero</td>
    <td><%= @app.family_hero %></td>
</tr>
 </table>
 </body>
 </html>